export enum GameStateEnum {
    BOOTSTRAP = 1,
    PAUSE,
    PLAYER_CREATION,
    MAP_CREATION,
    MAP_HOME_SYSTEM_SELECT,
    MAP_FIRST_RING_SELECT,
    MAP_SECOND_RING_SELECT,
    MAP_THIRD_RING_SELECT
}